build:
  image: node:18
  tags:
    - linux
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist

.test:
  stage: test
  dependencies:
    - build
  tags:
    - linux
  script:
    - npm ci
    - npm run test
  coverage: '/All files[ |]+(\d+\.\d+)/'

test-10:
  extends: .test
  image: node:10

test-18:
  extends: .test
  image: node:18

test-20:
  extends: .test
  image: node:20

test-22:
  extends: .test
  image: node:22
