.test:
  stage: test
  tags:
    - linux
  script:
    - npm ci
    - npm run build
    - npm run test
  coverage: '/All files[ |]+(\d+\.\d+)/'

test-12:
  extends: .test
  image: node:12

test-18:
  extends: .test
  image: node:18

test-20:
  extends: .test
  image: node:20

test-22:
  extends: .test
  image: node:22
